// PreemptionSpecifier
ATTR_KEYWORD(dso_local)

ATTR_KEYWORD(local_unnamed_addr)
ATTR_KEYWORD(unnamed_addr)
ATTR_KEYWORD(private)

// ParameterAttributes
ATTR_INT_KEYWORD(dereferenceable)

ATTR_KEYWORD(noundef)
ATTR_KEYWORD(noalias)
ATTR_KEYWORD(nocapture)
ATTR_KEYWORD(writeonly)
ATTR_KEYWORD(readonly)
ATTR_KEYWORD(inalloca)
ATTR_KEYWORD(readnone)
ATTR_KEYWORD(zeroext)
ATTR_KEYWORD(signext)
ATTR_KEYWORD(nonnull)
ATTR_KEYWORD(immarg)
